### ISSUE TITLE
Why I am getting Rendering problem?

### ISSUE THREAD

**Issue by nuhkoca** [JetradarMobile/desertplaceholder#2]
Hi,

I added your lib on my project but I am getting "The following classes could not be found:
- com.jetradar.desertplaceholder.DesertPlaceholder (Fix Build Path, Edit XML, Create Class)". How do I fix?

**Comment by johnkil** [comment]
oh, I fix it soon 😉

**Comment by squallsama** [comment]
You should use     <com.hotellook.desertplaceholder.DesertPlaceholder
        android:id="@+id/placeholder"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:buttonText="Add city"
        app:message="You don't have saved cities" />

**Comment by squallsama** [comment]
So looks like this library from hotellook developers. 

For my following works fine:

    <com.hotellook.desertplaceholder.DesertPlaceholder
        android:id="@+id/placeholder"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:buttonText="Add city"
        app:message="You don't have saved cities" />

**Comment by johnkil** [comment]
Fixed in [release 1.1.0](https://github.com/JetradarMobile/DesertPlaceholder/releases/tag/1.1.0)
