### ISSUE TITLE
Can I change moving animated objects with another things ?

### ISSUE THREAD

**Issue by suathh** [JetradarMobile/desertplaceholder#9]
Thanks for placeholder it is working very well. I am curious about if I can change moving ball,clouds etc ? Is there any way to do this ?

**Comment by johnkil** [comment]
@suathh Unfortunately this is not possible(

**Comment by rayliverified** [comment]
Not in the library but you can fork the code and replace the image assets yourself!

**Comment by suathh** [comment]
I will try and inform !

**Comment by petrovichtim** [comment]
I drew my objects over the canvas
